FROM node:24.16

RUN npm install -g pnpm

WORKDIR /app

COPY package*.json pnpm-workspace.yaml* prisma ./prisma ./

RUN pnpm install

COPY . .

RUN pnpm prisma generate

EXPOSE 3000

# Ejecutar en modo desarrollo
CMD ["pnpm", "run", "dev"]